const types = {
  SUBMIT_CONTACT: 'SUBMIT_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  UNDELETE_CONTACT: 'UNDELETE_CONTACT',
  INPUT_CHANGED: 'INPUT_CHANGED',
  INIT_CONTACTS: 'INIT_CONTACTS',
  NEXT_PAGE: 'NEXT_PAGE',
  PREV_PAGE: 'PREV_PAGE'
};

export default types;
